# Generated by Django 5.0.4 on 2024-04-14 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_newsletter_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='end_mail',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_mail',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала рассылки'),
        ),
    ]
