# Generated by Django 4.2 on 2024-04-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_client_owner_message_owner_newsletter_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('view_all_mails', 'Can view all newsletters'), ('deactivate_mails', 'Can deactivate newsletter')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
