# Generated by Django 4.2 on 2024-04-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_log_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='scheduled_time',
            field=models.TimeField(verbose_name='Время создания рассылки'),
        ),
    ]
