# Generated by Django 4.2 on 2024-04-18 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_alter_log_mailing_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='scheduled_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время создания рассылки'),
        ),
    ]
